### ISSUE TITLE
encoding issue

### ISSUE THREAD

**Issue by danielb75** [UNStats/DevInfoToDSD#2]
Ecountered the following issue when trying to write the csv file in memory to a file. Looks like there is some formating issue with indicator names having tab's in the description which is messing up the csv structure

See the screen grab of the error message

![devinfocsverror](https://user-images.githubusercontent.com/7405695/45181314-1a832280-b1ec-11e8-9ed0-d3588e84f6d0.jpg)

**Comment by apfister** [comment]
documenting here that the issue was that the source data in the access database had values in the rows with Tabs/Spaces. I will try to reproduce and look for a safeguard against this.

**Comment by apfister** [comment]
@danielb75 @gonzalezmorales 

I added in the `encoding='utf-8'` flag (example below) and the error disappears. can you try this out and let me know if all the data is still there and we aren't losing any records?

```
with open(output_path, 'w', encoding='utf-8', newline='') as csvfile:
```

**Comment by apfister** [comment]
going to close this with recent commits addressing potential encoding issues.
