### ISSUE TITLE
issues with geoJSON

### ISSUE THREAD

**Issue by gonzalezmorales** [UNStats/DevInfoToDSD#4]
![geojson lint](https://user-images.githubusercontent.com/7047819/45187424-9ab28380-b1fe-11e8-9cea-c4f9859cb0f2.png)

**Comment by apfister** [comment]
is this still an issue?

**Comment by apfister** [comment]
`'type': 'Feature'` added in 329d58c693e5b856f8c0264cf8e1d8f4cb7a25a0

also addressed the RFC spec that states the right-hand rule.
